### ISSUE TITLE
Request of new functions

### ISSUE THREAD

**Issue by LipoGamesBR** [pedrogiroldo/pomopy#1]
It would be interesting the function of being able to pause the timer temporarily, and then return to the paused time. 
Another thing would be to count the total uptime.

**Comment by pedrogiroldo** [comment]
I'll do it bro:)

**Comment by pedrogiroldo** [comment]
I've created a new branch with this function. It isn't ready, but you can test it.

**Comment by pedrogiroldo** [comment]
done
